import type { Metadata } from "next";
import "./globals.css";
import { montrealBook } from "@/fonts/fonts";
import Navbar from "@/components/ui/navbar/Navbar";
import Footer from "@/components/ui/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${montrealBook.className} bg-background text-foreground antialiased relative`}
      >
        <Navbar />
        <main className="px-6 min-h-screen">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
