import type { Metadata } from "next";
import "./globals.css";
import {
  montrealBook,
  montrealMedium,
  montrealThin,
  swily,
  viagram,
} from "@/fonts/fonts";
import Navbar from "@/components/ui/navbar/Navbar";
import Footer from "@/components/ui/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${montrealBook.variable} ${montrealMedium.variable} ${montrealThin.variable} ${swily.variable} ${viagram.variable}`}
    >
      <body className={`font-montrealBook bg-background text-foreground antialiased relative`}>
        <Navbar />
        <main className="px-6">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
