import type { Metadata } from "next";
import "./globals.css";
import {
  montrealBook,
  montrealMedium,
  montrealThin,
  swily,
  viagram,
} from "@/fonts/fonts";
import Navbar from "@/components/ui/navbar/Navbar";
import Footer from "@/components/ui/footer/Footer";
import { SmoothScroll } from "@/components/ui/lenis/SmoothScroll";
import SetID from "@/components/ui/user-identification/SetID";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${montrealBook.variable} ${montrealMedium.variable} ${montrealThin.variable} ${swily.variable} ${viagram.variable}`}
    >
      <body
        className={`font-montrealBook bg-background text-foreground antialiased relative verticalBar`}
      >
        <SetID />
        <SmoothScroll />
        <Navbar />
        <main className="px-6">{children}</main>
        <Footer />
        <Toaster
          closeButton
          toastOptions={{
            classNames: {
              toast:
                "items-start! font-montrealBook bg-background text-foreground",
              title: "uppercase text-sm! font-montrealMedium!",
              description: "text-[13px]! text-foreground/70!",
            },
          }}
        />
      </body>
    </html>
  );
}
